[package]
name = "embed-image"
version = "0.1.0"
edition = "2024"

[dependencies]
palc = "0.0.1"
zip = { version = "4.2.0", default-features = false, features = [
    "deflate",
    "zeroize",
] }

[profile.release]
strip = true
lto = true
codegen-units = 1
opt-level = 3
panic = "abort"
